### ISSUE TITLE
postgresql

### ISSUE THREAD

**Issue by kierangillen** [kierangillen/project4#2]
Hey there- I have two tables as seen here:

```
CREATE TABLE posts (
  id SERIAL PRIMARY KEY,
  group_id integer REFERENCES groups(id),
  username varchar REFERENCES users(username),
  media text NOT NULL,
  mediatype varchar NOT NULL,
  created_at TIMESTAMP DEFAULT current_timestamp
);

CREATE TABLE tags (
  id SERIAL PRIMARY KEY,
  name VARCHAR(32) NOT NULL,
  post_id integer REFERENCES posts(id),
  group_id integer REFERENCES groups(id)
);
``` 

I'm attempting to make a post to these two tables in one post from a front end post fetch. My problem is I dont know how to enter the data into the table 'tags' in the model because I dont yet have the 'post_id'. Is there a way to set up this schema where the post_id will get inserted automatically? Or do I need to make separate posts: one first to the table 'posts' and then once that SERIAL ID is created make a GET fetch to this table to get the ID and then make a second post to the tags table with the GET data? I can do this but it seems like there should be an easier way where I can just make one post. 

Thanks

@gittheking
@jasonseminara 
@rapala61 
@trevorpreston
@irwintsay

**Comment by gittheking** [comment]
@kierangillen you can use two middleware methods in your post route:
* First method to insert the post - (you can use the psql RETURNING id to get the id of the post you just entered see [here](http://stackoverflow.com/questions/19167349/postgresql-insert-from-select-returning-id)
* Second method to insert the tag.
