### ISSUE TITLE
issue with tags

### ISSUE THREAD

**Issue by kierangillen** [kierangillen/project4#3]
Hi there,
I'm having an issue with tags-

I'm trying to get the tag data in my app that references the regular post data set to filter out the data. I think I could do this with postgres and I've started down that route but it would be easier to do in the app and not change the schema I have now. 

I'm trying to do something like this:

```
  renderPosts() {
      this.props.tagsearchdata.forEach((tag, j)=> {
        this.props.postData.filter((result, i) => {
          return result.id === tag.post_id
          <TagPostItem
            GroupId={this.props.GroupId}
            mediaType={result.mediatype}
            handleDeletePostFunctions={this.props.handleDeletePostFunctions}
            userUserName={this.props.username}
            postUserName={result.username}
            postMedia={result.media}
            postTimeStamp={result.created_at}
            postId={result.id}
            key={i}
          />
        })
      })
    }
```

Thanks!
@gittheking @rapala61 @trevorpreston @irwintsay @mgershowitz

**Comment by rapala61** [comment]
Hi Kieran, can you close this issue, please? Thanks!
